package br.com.gestaoambiental.bean;
// Generated 21/05/2016 14:21:33 by Hibernate Tools 4.3.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.io.InputStream;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * Anexo generated by hbm2java
 */
@Entity
@Table(name = "anexo", catalog = "gestao_ambiental")
public class Anexo implements java.io.Serializable {

	private Integer anexId;
	private Documento documento;
	private String anexCaminho;
	private String nomeArquivo;
	private InputStream arquivo;

	public Anexo() {
	}

	public Anexo(Documento documento, String anexCaminho, String nomeArquivo) {
		this.documento = documento;
		this.anexCaminho = anexCaminho;
		this.nomeArquivo = nomeArquivo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "anex_id", unique = true, nullable = false)
	public Integer getAnexId() {
		return this.anexId;
	}

	public void setAnexId(Integer anexId) {
		this.anexId = anexId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "anex_id_documento")
	public Documento getDocumento() {
		return this.documento;
	}

	public void setDocumento(Documento documento) {
		this.documento = documento;
	}

	@Column(name = "anex_caminho", length = 100)
	public String getAnexCaminho() {
		return this.anexCaminho;
	}

	public void setAnexCaminho(String anexCaminho) {
		this.anexCaminho = anexCaminho;
	}

	@Column(name = "anex_nome_arquivo", length = 100)
	public String getNomeArquivo() {
		return nomeArquivo;
	}

	public void setNomeArquivo(String nomeArquivo) {
		this.nomeArquivo = nomeArquivo;
	}

	@Transient
	public InputStream getArquivo() {
		return arquivo;
	}

	public void setArquivo(InputStream arquivo) {
		this.arquivo = arquivo;
	}

}