package br.com.gestaoambiental.bean;
// Generated 23/04/2016 16:32:09 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Documento generated by hbm2java
 */
@Entity
@Table(name = "documento", catalog = "gestao_ambiental")
public class Documento implements java.io.Serializable {

	private Integer docuId;
	private Acesso acesso;
	private FormaProtecao formaProtecao;
	private LocalOrigem localOrigemByDocuIdLocalOrigem;
	private LocalOrigem localOrigemByDocuLocalGuarda;
	private ModuloRecuperacao moduloRecuperacao;
	private TempoGuarda tempoGuardaByDocuIdTempoGuarda;
	private TempoGuarda tempoGuardaByDocuIdTempoGuardaArquivoMorto;
	private Date docuDataManutencao;
	private String docuIdentificacao;
	private Set<Anexo> anexos = new HashSet<Anexo>(0);

	public Documento() {
	}

	public Documento(Acesso acesso, FormaProtecao formaProtecao, LocalOrigem localOrigemByDocuIdLocalOrigem,
			LocalOrigem localOrigemByDocuLocalGuarda, ModuloRecuperacao moduloRecuperacao,
			TempoGuarda tempoGuardaByDocuIdTempoGuarda, TempoGuarda tempoGuardaByDocuIdTempoGuardaArquivoMorto,
			Date docuDataManutencao, String docuIdentificacao, Set<Anexo> anexos) {
		this.acesso = acesso;
		this.formaProtecao = formaProtecao;
		this.localOrigemByDocuIdLocalOrigem = localOrigemByDocuIdLocalOrigem;
		this.localOrigemByDocuLocalGuarda = localOrigemByDocuLocalGuarda;
		this.moduloRecuperacao = moduloRecuperacao;
		this.tempoGuardaByDocuIdTempoGuarda = tempoGuardaByDocuIdTempoGuarda;
		this.tempoGuardaByDocuIdTempoGuardaArquivoMorto = tempoGuardaByDocuIdTempoGuardaArquivoMorto;
		this.docuDataManutencao = docuDataManutencao;
		this.docuIdentificacao = docuIdentificacao;
		this.anexos = anexos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "docu_id", unique = true, nullable = false)
	public Integer getDocuId() {
		return this.docuId;
	}

	public void setDocuId(Integer docuId) {
		this.docuId = docuId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "docu_id_acesso")
	public Acesso getAcesso() {
		return this.acesso;
	}

	public void setAcesso(Acesso acesso) {
		this.acesso = acesso;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "docu_forma_protecao")
	public FormaProtecao getFormaProtecao() {
		return this.formaProtecao;
	}

	public void setFormaProtecao(FormaProtecao formaProtecao) {
		this.formaProtecao = formaProtecao;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "docu_id_local_origem")
	public LocalOrigem getLocalOrigemByDocuIdLocalOrigem() {
		return this.localOrigemByDocuIdLocalOrigem;
	}

	public void setLocalOrigemByDocuIdLocalOrigem(LocalOrigem localOrigemByDocuIdLocalOrigem) {
		this.localOrigemByDocuIdLocalOrigem = localOrigemByDocuIdLocalOrigem;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "docu_local_guarda")
	public LocalOrigem getLocalOrigemByDocuLocalGuarda() {
		return this.localOrigemByDocuLocalGuarda;
	}

	public void setLocalOrigemByDocuLocalGuarda(LocalOrigem localOrigemByDocuLocalGuarda) {
		this.localOrigemByDocuLocalGuarda = localOrigemByDocuLocalGuarda;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "docu_id_modulo_recuperacao")
	public ModuloRecuperacao getModuloRecuperacao() {
		return this.moduloRecuperacao;
	}

	public void setModuloRecuperacao(ModuloRecuperacao moduloRecuperacao) {
		this.moduloRecuperacao = moduloRecuperacao;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "docu_id_tempo_guarda")
	public TempoGuarda getTempoGuardaByDocuIdTempoGuarda() {
		return this.tempoGuardaByDocuIdTempoGuarda;
	}

	public void setTempoGuardaByDocuIdTempoGuarda(TempoGuarda tempoGuardaByDocuIdTempoGuarda) {
		this.tempoGuardaByDocuIdTempoGuarda = tempoGuardaByDocuIdTempoGuarda;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "docu_id_tempo_guarda_arquivo_morto")
	public TempoGuarda getTempoGuardaByDocuIdTempoGuardaArquivoMorto() {
		return this.tempoGuardaByDocuIdTempoGuardaArquivoMorto;
	}

	public void setTempoGuardaByDocuIdTempoGuardaArquivoMorto(TempoGuarda tempoGuardaByDocuIdTempoGuardaArquivoMorto) {
		this.tempoGuardaByDocuIdTempoGuardaArquivoMorto = tempoGuardaByDocuIdTempoGuardaArquivoMorto;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "docu_data_manutencao", length = 10)
	public Date getDocuDataManutencao() {
		return this.docuDataManutencao;
	}

	public void setDocuDataManutencao(Date docuDataManutencao) {
		this.docuDataManutencao = docuDataManutencao;
	}

	@Column(name = "docu_identificacao", length = 100)
	public String getDocuIdentificacao() {
		return this.docuIdentificacao;
	}

	public void setDocuIdentificacao(String docuIdentificacao) {
		this.docuIdentificacao = docuIdentificacao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "documento")
	public Set<Anexo> getAnexos() {
		return this.anexos;
	}

	public void setAnexos(Set<Anexo> anexos) {
		this.anexos = anexos;
	}

}
