package br.com.gestaoambiental.bean;
// Generated 21/05/2016 14:21:33 by Hibernate Tools 4.3.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Documento generated by hbm2java
 */
@Entity
@Table(name = "documento", catalog = "gestao_ambiental")
public class Documento implements java.io.Serializable {

	private Integer docuId;
	private Acesso acesso;
	private LocalOrigem localOrigemByDocuIdLocalOrigem;
	private LocalOrigem localOrigemByDocuLocalGuarda;
	private Usuario usuario;
	private Date docuDataManutencao;
	private String docuIdentificacao;
	private String docuModRecuperacao;
	private String docuTempoGuarda;
	private String docuTempoGuardaArquivoMorto;
	private String docuFormaProtecao;
	private String docuObs;
	private Date docuDataCadastro;
	private String docuChave;
	private Set<Anexo> anexos = new HashSet<Anexo>(0);

	public Documento() {
	}

	public Documento(Acesso acesso, LocalOrigem localOrigemByDocuIdLocalOrigem,
			LocalOrigem localOrigemByDocuLocalGuarda, Usuario usuario, Date docuDataManutencao,
			String docuIdentificacao, String docuModRecuperacao, String docuTempoGuarda,
			String docuTempoGuardaArquivoMorto, String docuFormaProtecao, String docuObs, Date docuDataCadastro,
			String docuChave, Set<Anexo> anexos) {
		this.acesso = acesso;
		this.localOrigemByDocuIdLocalOrigem = localOrigemByDocuIdLocalOrigem;
		this.localOrigemByDocuLocalGuarda = localOrigemByDocuLocalGuarda;
		this.usuario = usuario;
		this.docuDataManutencao = docuDataManutencao;
		this.docuIdentificacao = docuIdentificacao;
		this.docuModRecuperacao = docuModRecuperacao;
		this.docuTempoGuarda = docuTempoGuarda;
		this.docuTempoGuardaArquivoMorto = docuTempoGuardaArquivoMorto;
		this.docuFormaProtecao = docuFormaProtecao;
		this.docuObs = docuObs;
		this.docuDataCadastro = docuDataCadastro;
		this.docuChave = docuChave;
		this.anexos = anexos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "docu_id", unique = true, nullable = false)
	public Integer getDocuId() {
		return this.docuId;
	}

	public void setDocuId(Integer docuId) {
		this.docuId = docuId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "docu_id_acesso")
	public Acesso getAcesso() {
		return this.acesso;
	}

	public void setAcesso(Acesso acesso) {
		this.acesso = acesso;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "docu_id_local_origem")
	public LocalOrigem getLocalOrigemByDocuIdLocalOrigem() {
		return this.localOrigemByDocuIdLocalOrigem;
	}

	public void setLocalOrigemByDocuIdLocalOrigem(LocalOrigem localOrigemByDocuIdLocalOrigem) {
		this.localOrigemByDocuIdLocalOrigem = localOrigemByDocuIdLocalOrigem;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "docu_local_guarda")
	public LocalOrigem getLocalOrigemByDocuLocalGuarda() {
		return this.localOrigemByDocuLocalGuarda;
	}

	public void setLocalOrigemByDocuLocalGuarda(LocalOrigem localOrigemByDocuLocalGuarda) {
		this.localOrigemByDocuLocalGuarda = localOrigemByDocuLocalGuarda;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "docu_id_usuario")
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "docu_data_manutencao", length = 10)
	public Date getDocuDataManutencao() {
		return this.docuDataManutencao;
	}

	public void setDocuDataManutencao(Date docuDataManutencao) {
		this.docuDataManutencao = docuDataManutencao;
	}

	@Column(name = "docu_identificacao", length = 100)
	public String getDocuIdentificacao() {
		return this.docuIdentificacao;
	}

	public void setDocuIdentificacao(String docuIdentificacao) {
		this.docuIdentificacao = docuIdentificacao;
	}

	@Column(name = "docu_mod_recuperacao")
	public String getDocuModRecuperacao() {
		return this.docuModRecuperacao;
	}

	public void setDocuModRecuperacao(String docuModRecuperacao) {
		this.docuModRecuperacao = docuModRecuperacao;
	}

	@Column(name = "docu_tempo_guarda")
	public String getDocuTempoGuarda() {
		return this.docuTempoGuarda;
	}

	public void setDocuTempoGuarda(String docuTempoGuarda) {
		this.docuTempoGuarda = docuTempoGuarda;
	}

	@Column(name = "docu_tempo_guarda_arquivo_morto")
	public String getDocuTempoGuardaArquivoMorto() {
		return this.docuTempoGuardaArquivoMorto;
	}

	public void setDocuTempoGuardaArquivoMorto(String docuTempoGuardaArquivoMorto) {
		this.docuTempoGuardaArquivoMorto = docuTempoGuardaArquivoMorto;
	}

	@Column(name = "docu_forma_protecao")
	public String getDocuFormaProtecao() {
		return this.docuFormaProtecao;
	}

	public void setDocuFormaProtecao(String docuFormaProtecao) {
		this.docuFormaProtecao = docuFormaProtecao;
	}

	@Column(name = "docu_obs", length = 500)
	public String getDocuObs() {
		return this.docuObs;
	}

	public void setDocuObs(String docuObs) {
		this.docuObs = docuObs;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "docu_data_cadastro", length = 10)
	public Date getDocuDataCadastro() {
		return this.docuDataCadastro;
	}

	public void setDocuDataCadastro(Date docuDataCadastro) {
		this.docuDataCadastro = docuDataCadastro;
	}

	@Column(name = "docu_chave", length = 20)
	public String getDocuChave() {
		return this.docuChave;
	}

	public void setDocuChave(String docuChave) {
		this.docuChave = docuChave;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "documento")
	public Set<Anexo> getAnexos() {
		return this.anexos;
	}

	public void setAnexos(Set<Anexo> anexos) {
		this.anexos = anexos;
	}

}
