package br.com.gestaoambiental.bean;
// Generated 15/05/2016 16:28:26 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Filial generated by hbm2java
 */
@Entity
@Table(name = "filial", catalog = "gestao_ambiental")
public class Filial implements java.io.Serializable {

	private Integer filiId;
	private Empresa empresa;
	private String filiNome;

	public Filial() {
	}

	public Filial(Empresa empresa, String filiNome) {
		this.empresa = empresa;
		this.filiNome = filiNome;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "fili_id", unique = true, nullable = false)
	public Integer getFiliId() {
		return this.filiId;
	}

	public void setFiliId(Integer filiId) {
		this.filiId = filiId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fili_id_empresa")
	public Empresa getEmpresa() {
		return this.empresa;
	}

	public void setEmpresa(Empresa empresa) {
		this.empresa = empresa;
	}

	@Column(name = "fili_nome", length = 45)
	public String getFiliNome() {
		return this.filiNome;
	}

	public void setFiliNome(String filiNome) {
		this.filiNome = filiNome;
	}

}
