package br.com.gestaoambiental.bean;

// Generated 23/04/2016 16:32:09 by Hibernate Tools 4.3.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * LocalOrigem generated by hbm2java
 */
@Entity
@Table(name = "local_origem", catalog = "gestao_ambiental")
public class LocalOrigem implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer loorId;
	private String loorDescricao;
	private Set<Documento> documentosForDocuIdLocalOrigem = new HashSet<Documento>(
			0);
	private Set<Documento> documentosForDocuLocalGuarda = new HashSet<Documento>(
			0);

	public LocalOrigem() {
	}

	public LocalOrigem(String loorDescricao,
			Set<Documento> documentosForDocuIdLocalOrigem,
			Set<Documento> documentosForDocuLocalGuarda) {
		this.loorDescricao = loorDescricao;
		this.documentosForDocuIdLocalOrigem = documentosForDocuIdLocalOrigem;
		this.documentosForDocuLocalGuarda = documentosForDocuLocalGuarda;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "loor_id", unique = true, nullable = false)
	public Integer getLoorId() {
		return this.loorId;
	}

	public void setLoorId(Integer loorId) {
		this.loorId = loorId;
	}

	@Column(name = "loor_descricao", length = 50)
	public String getLoorDescricao() {
		return this.loorDescricao;
	}

	public void setLoorDescricao(String loorDescricao) {
		this.loorDescricao = loorDescricao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "localOrigemByDocuIdLocalOrigem")
	public Set<Documento> getDocumentosForDocuIdLocalOrigem() {
		return this.documentosForDocuIdLocalOrigem;
	}

	public void setDocumentosForDocuIdLocalOrigem(
			Set<Documento> documentosForDocuIdLocalOrigem) {
		this.documentosForDocuIdLocalOrigem = documentosForDocuIdLocalOrigem;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "localOrigemByDocuLocalGuarda")
	public Set<Documento> getDocumentosForDocuLocalGuarda() {
		return this.documentosForDocuLocalGuarda;
	}

	public void setDocumentosForDocuLocalGuarda(
			Set<Documento> documentosForDocuLocalGuarda) {
		this.documentosForDocuLocalGuarda = documentosForDocuLocalGuarda;
	}

}
