package br.com.gestaoambiental.bean;
// Generated 15/05/2016 16:28:26 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "usuario", catalog = "gestao_ambiental")
public class Usuario implements java.io.Serializable {

	private Integer usuaId;
	private Empresa empresa;
	private String usuaNome;
	private String usuaUsuario;
	private String usuaSenha;

	public Usuario() {
	}

	public Usuario(Empresa empresa, String usuaNome, String usuaUsuario, String usuaSenha) {
		this.empresa = empresa;
		this.usuaNome = usuaNome;
		this.usuaUsuario = usuaUsuario;
		this.usuaSenha = usuaSenha;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "usua_id", unique = true, nullable = false)
	public Integer getUsuaId() {
		return this.usuaId;
	}

	public void setUsuaId(Integer usuaId) {
		this.usuaId = usuaId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usua_id_empresa")
	public Empresa getEmpresa() {
		return this.empresa;
	}

	public void setEmpresa(Empresa empresa) {
		this.empresa = empresa;
	}

	@Column(name = "usua_nome", length = 45)
	public String getUsuaNome() {
		return this.usuaNome;
	}

	public void setUsuaNome(String usuaNome) {
		this.usuaNome = usuaNome;
	}

	@Column(name = "usua_usuario", length = 45)
	public String getUsuaUsuario() {
		return this.usuaUsuario;
	}

	public void setUsuaUsuario(String usuaUsuario) {
		this.usuaUsuario = usuaUsuario;
	}

	@Column(name = "usua_senha", length = 45)
	public String getUsuaSenha() {
		return this.usuaSenha;
	}

	public void setUsuaSenha(String usuaSenha) {
		this.usuaSenha = usuaSenha;
	}

}
