package br.com.gestaoambiental.bean;
// Generated 21/05/2016 14:21:33 by Hibernate Tools 4.3.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "usuario", catalog = "gestao_ambiental")
public class Usuario implements java.io.Serializable {

	private Integer usuaId;
	private Empresa empresa;
	private String usuaNome;
	private String usuaUsuario;
	private String usuaSenha;
	private String usuaNivel;
	private Set<Documento> documentos = new HashSet<Documento>(0);

	public Usuario() {
	}

	public Usuario(Empresa empresa, String usuaNome, String usuaUsuario, String usuaSenha, String usuaNivel,
			Set<Documento> documentos) {
		this.empresa = empresa;
		this.usuaNome = usuaNome;
		this.usuaUsuario = usuaUsuario;
		this.usuaSenha = usuaSenha;
		this.usuaNivel = usuaNivel;
		this.documentos = documentos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "usua_id", unique = true, nullable = false)
	public Integer getUsuaId() {
		return this.usuaId;
	}

	public void setUsuaId(Integer usuaId) {
		this.usuaId = usuaId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "usua_id_empresa")
	public Empresa getEmpresa() {
		return this.empresa;
	}

	public void setEmpresa(Empresa empresa) {
		this.empresa = empresa;
	}

	@Column(name = "usua_nome", length = 45)
	public String getUsuaNome() {
		return this.usuaNome;
	}

	public void setUsuaNome(String usuaNome) {
		this.usuaNome = usuaNome;
	}

	@Column(name = "usua_usuario", length = 45)
	public String getUsuaUsuario() {
		return this.usuaUsuario;
	}

	public void setUsuaUsuario(String usuaUsuario) {
		this.usuaUsuario = usuaUsuario;
	}

	@Column(name = "usua_senha", length = 45)
	public String getUsuaSenha() {
		return this.usuaSenha;
	}

	public void setUsuaSenha(String usuaSenha) {
		this.usuaSenha = usuaSenha;
	}

	@Column(name = "usua_nivel", length = 20)
	public String getUsuaNivel() {
		return this.usuaNivel;
	}

	public void setUsuaNivel(String usuaNivel) {
		this.usuaNivel = usuaNivel;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<Documento> getDocumentos() {
		return this.documentos;
	}

	public void setDocumentos(Set<Documento> documentos) {
		this.documentos = documentos;
	}

}
